# Generated by Django 5.1.5 on 2025-05-23 12:24

import django.db.models.deletion
import kaileys_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=kaileys_app.models.default_expiry)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaileys_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaileys_app.course')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaileys_app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('courses', models.ManyToManyField(through='kaileys_app.AccessGrant', to='kaileys_app.course')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaileys_app.organization')),
            ],
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaileys_app.trainee'),
        ),
    ]
