# Generated by Django 5.1.5 on 2025-05-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaileys_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('fire_safety', 'FIRE_SAFETY_TRAINING_KAILEYS'), ('first_aid', 'FIRST_AID'), ('safety_committee', 'SAFETY_AND_HEALTH_COMMITTEE_TRAINING')], max_length=100, unique=True),
        ),
    ]
