# Generated by Django 5.1.5 on 2025-05-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaileys_app', '0002_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
