# Generated by Django 5.1.5 on 2025-05-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaileys_app', '0003_alter_accesscode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('fire_safety', 'Fire Safety Training'), ('first_aid', 'First Aid'), ('safety_committee', 'Safety and Health Committee Training')], db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='trainee',
            unique_together={('phone_number', 'organization')},
        ),
    ]
