# Generated by Django 5.2.1 on 2025-06-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaileys_app', '0004_alter_accesscode_code_alter_course_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessCode',
        ),
    ]
