# Generated by Django 5.1.5 on 2025-06-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaileys_app', '0005_delete_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
