# Generated by Django 5.1.5 on 2025-06-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaileys_app', '0008_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('fire_safety', 'Fire Safety Training'), ('first_aid', 'First Aid'), ('safety_committee', 'Safety and Health Committee Training'), ('chemical_safety', 'Chemical Safety'), ('scaffolding_safety', 'Scaffolding, Ladder Safety and Work at Height Training')], db_index=True, max_length=100, unique=True),
        ),
    ]
