# Generated by Django 5.2.1 on 2026-06-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kaileys_app", "0011_create_default_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="access_code",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
