# Generated by Django 5.2.1 on 2026-06-21 14:43

import kaileys_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kaileys_app", "0012_course_access_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainee",
            name="courses",
        ),
        migrations.AddField(
            model_name="course",
            name="access_code_expires_at",
            field=models.DateTimeField(default=kaileys_app.models.default_code_expiry),
        ),
        migrations.DeleteModel(
            name="AccessGrant",
        ),
    ]
